### ISSUE TITLE
sidebar - Can't add anything below oneliners

### ISSUE THREAD

**Issue by l1th0** [echicken/synchronet-web-v4#12] opened 2017-07-21 18:49 UTC
On the ecweb4 sidebar, you can add additional items.  For instance, if you have 01-whos online, and 03-system info, and 04-oneliners then you can add a new item such as a picture by creating a new file and calling it 02-picture.   This will show up correctly in-between the 01-who's online and 03-system info on the sidebar.

If you try to put any additional sidebar items under 04-oneliners, then the item will not show up.  I have tried reviewing the code for the oneliners JavaScript app to see if there were unclosed tables or such but everything looked normal.   It's hard to tell where this issue is coming from.  It would be nice to be able to put additional advertisements, pictures, and web widgets under the oneliners plug-in.

**Comment by echicken** [comment] 2017-07-21 19:45
I can't reproduce this on my end, though I'm slightly mystified by some choices I made in the code, so who knows.

If you could provide a link to your site, I'll take a look and see if I can notice anything weird on the front end.  I'll also commit a change here shortly, but I'm not optimistic that it'll make any difference for you.

What is the extension of the file you're trying to include?  What are its contents?  Can you try creating a file at 'web/root/sidebar/05-test.html' containing only the word 'test' and see if that gets included?

**Comment by l1th0** [comment] 2017-07-21 20:10
The website is www.asirta.com   

I created a standard 002-test.xjs file and put it in the sidebar directory as requested.   You can see on the sidebar there is a "synthwave mix" picture which links back to Bandcamp.  This is an embedded link put into an .xjs file read as an <html>.  You can see on the site that the "synthhave mix" side widget works fine in-between the nodelist and system stats .xjs files.  This file is named 002-test.xjs.

For testing, I put the exact same widget as the one that shows up in-between the nodelist and system stats after the oneliners.   I changed the file name from 002-test.xjs to 004-test.xjs (or 005 same results).   When I do this, it does not show up after the oneliners.  Also, there is no .ssjs temp file created for the 004-test.xjs file suggesting that the 004-test.xjs file is not being read at all when generating the sidebar.  So any file placed after the oneliners will not be read including the systemstats.xjs and nodelist.xjs if these are put after the oneliners.

Also, note I am running synchronet 3.16c with the version of ecweb4 which is made for 3.16c.  I am using  the most current oneliners code from the repository.  The same problem persists using the original oneliners code as well.  

If it is found that it works using the most current ecweb4 with 3.17, then my option would be to upgrade.  But, would prefer to stick to what I have for a couple more months.

**Comment by echicken** [comment] 2017-07-21 20:26
There has never been a release of this web interface, so there's no 3.16c compatible 'version' per se.  It's difficult to say what has changed between when you installed it and now, however nothing in the sidebar-loading part looks like it would be incompatible with 3.16c.

You could back up your current 'web/lib/sidebar.js' file and replace it with the latest one from this repository.  This may help, and I don't think it'll cause any problems.  If that does the job, we'll leave it there (I'm not expending much effort on 3.16c compatibility at this point).

If that doesn't help the dates of your current 'web/lib/sidebar.js' and 'web/root/index.xjs' files might be enough for me to go on to look back and see what's changed.

**Comment by l1th0** [comment] 2017-07-21 20:34
ok, I will do your suggestions.  Once I upgrade to 3.17, and if the same problem persists with the new ecweb4, then will re-address it then.  Thanks!

**Comment by DesotoFireflite** [comment] 2017-07-21 20:40
>>> For testing, I put the exact same widget as the one that shows up in-between the nodelist and system stats after the oneliners. I changed the file name from 002-test.xjs to 004-test.xjs (or 005 same results). When I do this, it does not show up after the oneliners. Also, there is no .ssjs temp file created for the 004-test.xjs file suggesting that the 004-test.xjs file is not being read at all when generating the sidebar. So any file placed after the oneliners will not be read including the systemstats.xjs and nodelist.xjs if these are put after the oneliners. <<<

Sorry for butting in, but when I was testing ecwebv4, I tried to test it using several of the same names, but with different numbers, and they would not show up. I found I had to use different names. Hope this helps


-------- Original Message --------

**Comment by l1th0** [comment] 2017-07-21 20:45
Looks like updating the sidebar.js worked!   I appreciate the help,

**Comment by DesotoFireflite** [comment] 2017-07-21 20:46
Awesome, 


-------- Original Message --------

**Comment by echicken** [comment] 2017-07-22 21:16
Okay, I'll close this issue now; evidently it was caused by something that has since been fixed.

For what it's worth, there should be no problem with having files with the same name but a different prefix number at the start of the filename; maybe that was an issue with an earlier version of 'lib/sidebar.js' ... I dunno.

**Closed by echicken** 2017-07-22 21:16 UTC
